name: Multiarch OCI image

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  multiarch-build:
    name: Build multi-architecture image
    runs-on: ubuntu-22.04

    env:
      SOURCE_DATE_EPOCH: "315532800"

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - run: podman version
      - run: buildah version
      - run: make images

      - name: Upload compiled binary
        uses: actions/upload-artifact@v3
        with:
          name: context.amd64.tar
          path: .build/1.4.3+k0s.latest-315532800/context.amd64.tar

      - run: make oci-manifest
      - run: podman run --rm -- "$(cat .build/*/manifest.iid)"
