name: Multiarch image

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  multiarch-build:
    name: Build multi-architecture image
    runs-on: ubuntu-22.04

    env:
      SOURCE_DATE_EPOCH: "315532800"

    steps:
      - name: Install Podman v4.2.0
        # https://github.com/containers/podman/issues/14065#issuecomment-1221549603
        run: |
          wget http://ftp.us.debian.org/debian/pool/main/libp/libpod/podman_4.2.0+ds1-3_amd64.deb
          sudo dpkg -i podman_4.2.0+ds1-3_amd64.deb
          mkdir -p ~/.config/containers
          echo '[storage]' >> ~/.config/containers/storage.conf
          echo 'driver = "overlay"' >> ~/.config/containers/storage.conf
          podman version

      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: 'Make: OCI manifest'
        timeout-minutes: 10
        run: make oci-manifest

      - name: List local images
        if: always()
        run: podman images --format "table {{.ID}} {{.Repository}} {{.Tag}} {{.Labels}} {{.Digest}}"

      - name: 'Smoke test: Run manifest'
        run: podman run --rm -- "$(cat .build/*/manifest.iid)"
